<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use App\Models\Tiket;

class tiket_dummy_seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Tiket::insert([
            [
                'tiket_id' => 'IN170225440',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_ME-D4-WSB_DOWN_REGTSEL5',
                'witel_id' => 7,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 11:18')->toDateTimeString(),
                'mttr' => 3.81,
                'jml_site' => 2,
                'root_cause' => 'TERTABRAK KENDARAAN',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170230444',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_ME9-D4-KBU_DOWN_REGTSEL5',
                'witel_id' => 1,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '1/12/2023, 02:49')->toDateTimeString(),
                'mttr' => 3.5,
                'jml_site' => 2,
                'root_cause' => 'VANDALISME',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170236594',
                'headline' => 'TSEL_METRO_8NODEB_UNDER_GPON00-D4-LSE-3FD_DOWN_REG...',
                'witel_id' => 6,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 11:18')->toDateTimeString(),
                'mttr' => 2.31,
                'jml_site' => 8,
                'root_cause' => 'PEKERJAAN PIHAK KE3-BEGO',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170236641',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_GPON02-D4-KLX-3_DOWN_REGTS...',
                'witel_id' => 3,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 11:22')->toDateTimeString(),
                'mttr' => 5.41,
                'jml_site' => 2,
                'root_cause' => 'TERTABRAK KENDARAAN',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170240224',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_GPON00-D4-LSE-3FD_DOWN_REG...',
                'witel_id' => 6,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 16:45')->toDateTimeString(),
                'mttr' => 0.62,
                'jml_site' => 2,
                'root_cause' => 'PEKERJAAN PIHAK KE3-BEGO',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170240225',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_GPON00-D4-LSE-3FD_DOWN_REG...',
                'witel_id' => 6,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 16:45')->toDateTimeString(),
                'mttr' => 0.65,
                'jml_site' => 2,
                'root_cause' => 'PEKERJAAN PIHAK KE3-BEGOoooo',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170240226',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_GPON00-D4-LSE-3FD_DOWN_REG...',
                'witel_id' => 6,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 16:45')->toDateTimeString(),
                'mttr' => 3.1,
                'jml_site' => 2,
                'root_cause' => 'PEKERJAAN BEGO',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170240227',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_GPON00-D4-LSE-3FD_DOWN_REG...',
                'witel_id' => 6,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 16:45')->toDateTimeString(),
                'mttr' => 5.26,
                'jml_site' => 2,
                'root_cause' => 'PIHAK KE3-BEGO',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170240228',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_GPON00-D4-LSE-3FD_DOWN_REG...',
                'witel_id' => 6,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 16:45')->toDateTimeString(),
                'mttr' => 0.00,
                'jml_site' => 2,
                'root_cause' => 'VANDALISME',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170240229',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_GPON00-D4-LSE-3FD_DOWN_REG...',
                'witel_id' => 6,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 16:45')->toDateTimeString(),
                'mttr' => 0.00,
                'jml_site' => 2,
                'root_cause' => 'TERTABRAK KENDARAAN BESAR',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170240230',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_GPON00-D4-LSE-3FD_DOWN_REG...',
                'witel_id' => 6,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 16:45')->toDateTimeString(),
                'mttr' => 0.00,
                'jml_site' => 2,
                'root_cause' => 'KENA PETIR',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170240231',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_GPON00-D4-LSE-3FD_DOWN_REG...',
                'witel_id' => 6,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 16:45')->toDateTimeString(),
                'mttr' => 0.00,
                'jml_site' => 2,
                'root_cause' => 'KESENGGOL BUS',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170240232',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_GPON00-D4-LSE-3FD_DOWN_REG...',
                'witel_id' => 6,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 16:45')->toDateTimeString(),
                'mttr' => 0.00,
                'jml_site' => 2,
                'root_cause' => 'PEKERJAAN MALAS',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170240233',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_GPON00-D4-LSE-3FD_DOWN_REG...',
                'witel_id' => 6,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 16:45')->toDateTimeString(),
                'mttr' => 0.00,
                'jml_site' => 2,
                'root_cause' => 'PEKERJA TELAT',
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'tiket_id' => 'IN170240234',
                'headline' => 'TSEL_METRO_2NODEB_UNDER_GPON00-D4-LSE-3FD_DOWN_REG...',
                'witel_id' => 6,
                'tgl_open' => Carbon::createFromFormat('j/n/Y, H:i', '2/12/2023, 16:45')->toDateTimeString(),
                'mttr' => 0.00,
                'jml_site' => 2,
                'root_cause' => 'PEKERJAAN PIHAK KE3-BEGO',
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);
    }
}
